name: Test on Pull Requests

on:
    pull_request:
        branches:
            - main

jobs:
    unit-test:
        name: Run Unit Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.14
                  cache: "yarn"

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run Unit Tests
              run: yarn test:ci

    e2e-test:
        name: Run E2E Tests
        runs-on: ubuntu-latest
        needs: unit-test # Only run if unit tests pass

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.14
                  cache: "yarn"

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Install Cypress Binary
              run: yarn cypress install

            - name: Run Cypress Tests
              uses: cypress-io/github-action@v6
              with:
                  with:
                  build: yarn build
                  start: yarn start
                  wait-on: http://localhost:3000 # Wait for server before running tests
                  browser: chrome
